# Generated by Django 5.2.13 on 2026-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Background image for the cinematic invitation page'),
        ),
        migrations.AddField(
            model_name='group',
            name='mission_statement',
            field=models.TextField(blank=True, help_text='Cinematic mission or slogan for invitations'),
        ),
    ]
