# Generated by Django 5.2.13 on 2026-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_hero_image_url_group_mission_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of group interests/activities'),
        ),
    ]
